#!/usr/bin/env bash

set -e

# Allow alternative configs to be passed (i.e. for different OSs)
if [ -z "${DOTBOT_INSTALL}" ]; then
  echo "Please specify a $DOTBOT_INSTALL file. ('export DOTBOT_INSTALL=<filename>')"
  exit 1
fi

echo "Installing from $DOTBOT_INSTALL"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${DOTBOT_INSTALL}" "${@}"
