#!/usr/bin/env bash

set -e

# Allow alternative configs to be passed (i.e. for different OSs)
CONFIG="install.conf.json"
if [ -n "$1" ]
  then
    CONFIG=$1
fi

echo "Installing from ${CONFIG}"

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
