###########################################
#       Setup Linux Specific Stuff        #
###########################################

# MacOS doesn't support the more thorough colors format, but you can install gls with coreutils which does!
eval "$(gdircolors ~/.dir_colors)"

###########################################
#        Setup Core Configuration         #
###########################################
source "./.zshrc.core"
