[chromecast]
devices = [ "Living Room TV", "Basement Mini", "Guest Room Speaker", "Kitchen Speaker", "Living Room TV Group", "Party Group", "Bedroom TV", "Basement Speaker", "Downstairs", "Upstairs", "Everywhere",]
app_whitelist = [ "Google Play Music",]
retry_missing = true

[lastfm]
user_name = "<username>"
password = "<password>"
api_key = "<key>"
api_secret = "<secret>"
